arm_id:                           $(arg arm_id)
m_ee:                             0.76                # [kg]
singularity_warning_threshold:    0.001               # print a warning if the smallest singular value of J x J^T drops below this value (use -1 to disable)

franka_gripper:
  type:    franka_gazebo/FrankaGripperSim
  arm_id:  $(arg arm_id)

  finger1:
    gains: { p: 100, i: 25, d: 20 }

  finger2:
    gains: { p: 100, i: 25, d: 20 }
