arm_id: $(arg arm_id)

franka_gripper:
  type:    franka_gazebo/FrankaGripperSim

  finger1:
    joint: $(arg arm_id)_finger_joint1
    gains: { p: 100, i: 25, d: 20 }

  finger2:
    joint: $(arg arm_id)_finger_joint2
    gains: { p: 100, i: 25, d: 20 }
